# Generated by Django 5.2.3 on 2025-07-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_content_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_content',
            new_name='content',
        ),
    ]
